# Generated by Django 4.0.4 on 2022-05-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0002_userdata_commonpacksopened_userdata_defeat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='commonPacksOpened',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='rarePacksOpened',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='specialPacksOpened',
        ),
    ]
