# Generated by Django 4.0.4 on 2022-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0003_remove_userdata_commonpacksopened_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='newUser',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
