# Generated by Django 4.0.4 on 2022-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0004_remove_userdata_newuser_alter_userdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cards',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='defeat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='money',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='win',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
