# Generated by Django 4.0.4 on 2022-05-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0005_alter_userdata_cards_alter_userdata_defeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('name', models.TextField(default=' ', null=True)),
                ('image', models.TextField(default=' ', null=True)),
                ('attack', models.IntegerField(default=0, null=True)),
                ('health', models.IntegerField(default=0, null=True)),
                ('rarity', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='cards',
        ),
    ]
