# Generated by Django 4.0.4 on 2022-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0006_userscards_remove_userdata_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cards',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
