# Generated by Django 4.0.4 on 2022-05-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0007_userdata_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscards',
            name='card_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
