# Generated by Django 4.0.4 on 2022-05-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_cards_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='image',
            field=models.BinaryField(default=b''),
        ),
    ]
